/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.lab2;

import javax.swing.JOptionPane;

/**
 *
 * @author SANDOVAL
 */
public class Prueba extends javax.swing.JFrame {

    String nombre;
    int edad;
    double cedula;
    int tamaño;

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Programa4 = new javax.swing.JButton();
        Teclado1 = new javax.swing.JTextField();
        Cedula = new javax.swing.JTextField();
        GeneradorNombre = new javax.swing.JTextField();
        GeneradorEdad = new javax.swing.JTextField();
        BtnCedula = new javax.swing.JButton();
        AgregarNombre = new javax.swing.JButton();
        Edad = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Tamaño = new javax.swing.JTextField();
        BtnTamaño = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Programa4.setText("Agregar");
        Programa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Programa4ActionPerformed(evt);
            }
        });

        Teclado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Teclado1ActionPerformed(evt);
            }
        });

        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });

        GeneradorEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneradorEdadActionPerformed(evt);
            }
        });

        BtnCedula.setText("Agregar Cedula");
        BtnCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCedulaActionPerformed(evt);
            }
        });

        AgregarNombre.setText("AgregarNombre");
        AgregarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNombreActionPerformed(evt);
            }
        });

        Edad.setText("Agregar Edad");
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });

        jLabel1.setText("Agregar el tamaño del arreglo");

        BtnTamaño.setText("Agregar");
        BtnTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTamañoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tamaño)
                                .addGap(3, 3, 3)
                                .addComponent(BtnTamaño)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Teclado1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Programa4)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AgregarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GeneradorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GeneradorEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Teclado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Programa4)
                    .addComponent(Tamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTamaño))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneradorEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GeneradorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCedula)
                    .addComponent(Edad)
                    .addComponent(AgregarNombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Programa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Programa4ActionPerformed
        // TODO add your handling code here:
       

        Persona arreglo1[] = new Persona[tamaño];

        for (int i = 1; i < arreglo1.length; i++) {

            arreglo1[i] = new Persona(cedula, nombre, edad);

        }

        for (int j = 0; j < arreglo1.length; j++) {
            System.out.println("-----------------------");
            System.out.println("Cedula   nombre   edad  ");
            System.out.println(arreglo1[j].getcedula() + "   " + arreglo1[j].getnombre() + "   " + arreglo1[j].getedad());

        }
    }//GEN-LAST:event_Programa4ActionPerformed

    private void BtnCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCedulaActionPerformed
        // TODO add your handling code here:
        try {
            String cadena = Cedula.getText();
            double cedula = Double.parseDouble(Cedula.getText());
            this.cedula = cedula;
            if (cadena.length() > 0) {
                cadena = cadena.substring(0, 0);
                Cedula.setText(cadena);

            }
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_BtnCedulaActionPerformed

    private void AgregarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNombreActionPerformed
        // TODO add your handling code here:
        String nombre = GeneradorNombre.getText();
        this.nombre = nombre;
        String cadena = GeneradorNombre.getText();
        if (cadena.length() > 0) {
            cadena = cadena.substring(0, 0);
            GeneradorNombre.setText(cadena);

        }

    }//GEN-LAST:event_AgregarNombreActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
        try {
            String cadena = GeneradorEdad.getText();
            int edad = Integer.parseInt(GeneradorEdad.getText());
            this.edad = edad;
            if (cadena.length() > 0) {
                cadena = cadena.substring(0, 0);
                GeneradorEdad.setText(cadena);

            }
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_EdadActionPerformed

    private void GeneradorEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneradorEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneradorEdadActionPerformed

    private void Teclado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Teclado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Teclado1ActionPerformed

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaActionPerformed

    private void BtnTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTamañoActionPerformed
        // TODO add your handling code here:
        
        int tamaño=Integer.parseInt(Tamaño.getText());
        this.tamaño=tamaño;
        
        
        
        
    }//GEN-LAST:event_BtnTamañoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarNombre;
    private javax.swing.JButton BtnCedula;
    private javax.swing.JButton BtnTamaño;
    private javax.swing.JTextField Cedula;
    private javax.swing.JButton Edad;
    private javax.swing.JTextField GeneradorEdad;
    private javax.swing.JTextField GeneradorNombre;
    private javax.swing.JButton Programa4;
    private javax.swing.JTextField Tamaño;
    private javax.swing.JTextField Teclado1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
